Repository ublue-os/bluefin-lts, pull requests merged in 2025-05, with the labels that each got.

#475 fix: ignore readymade config for bluefin on base bluefin LTS builds
  build_scripts/20-packages.sh
Labels: size:XS, lgtm

#476 feat: add libvirtd with ublue workaround
  build_scripts/overrides/dx/00-packages.sh
Labels: enhancement, size:XS, lgtm

#474 Revert "Revert "fix: disable distrobox module on uupd""
  build_scripts/40-services.sh
Labels: size:XS, lgtm

#477 fix(arm): remove pixi for now
  build_scripts/overrides/aarch64/05-pixi.sh
Labels: size:S, lgtm, arm

#478 fix: ensure qemu-kvm present for libvirtd use
  build_scripts/overrides/dx/00-packages.sh
Labels: dx, size:XS, lgtm

#480 fix: use ujust update recipe from bluefin proper
  system_files/usr/share/ublue-os/just/10-update.just
Labels: size:S, lgtm

#407 feat: use inputs for rechunking and sbom generation (+ cleanup)
  .github/workflows/build-dx.yml
  .github/workflows/build-gdx.yml
  .github/workflows/build-regular.yml
  .github/workflows/reusable-build-image.yml
Labels: enhancement, size:L, lgtm

#485 fix(ci): remove docker login from manifest step
  .github/workflows/reusable-build-image.yml
Labels: size:XS, lgtm

#482 refactor: use `dnf copr` where feasible
  build_scripts/20-packages.sh
Labels: enhancement, size:S, lgtm

#487 fix(CI): copy login auth to docker location for cosign
  .github/workflows/reusable-build-image.yml
Labels: dx, size:XS, lgtm

#490 feat: enable ublue-brew for aarch64
  build_scripts/20-packages.sh
  build_scripts/40-services.sh
  build_scripts/overrides/x86_64/10-brew.sh
Labels: enhancement, size:S, lgtm

#497 fix: update docker extension to container extension
  system_files_overrides/dx/usr/share/ublue-os/user-setup.hooks.d/11-vscode.sh
Labels: dx, size:XS, lgtm

#495 fix: working vscode install GPG check
  build_scripts/overrides/dx/00-packages.sh
Labels: bug, dx, size:XS, lgtm
