Repository ublue-os/bluefin-lts, pull requests merged in 2025-08, with the labels that each got.

#615 feat: add gradia and smile by default
  system_files/etc/ublue-os/system-flatpaks.list
Labels: enhancement, size:XS, lgtm

#624 fix(ci): don't build GDX hwe since it doesn't exist
  .github/workflows/build-iso.yml
Labels: size:XS, lgtm, gdx

#627 Update README.md
  README.md
Labels: documentation, size:XS, lgtm

#641 docs: create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, size:XS, lgtm

#646 chore: Cleanup and improve changelogs.py
  .github/changelogs.py
  .gitignore
Labels: dx, size:L, lgtm

#666 feat: add rclone and restic
  build_scripts/20-packages.sh
Labels: enhancement, size:S, lgtm
