Repository ublue-os/bluefin-lts, pull requests merged in 2025-03, with the labels that each got.

#356 fix: get gpg checking for vscode + ensure docker/podman sockets are enabled
  build_scripts/build.sh
  build_scripts/overrides/dx/00-packages.sh
  build_scripts/overrides/dx/20-services.sh
Labels: size:M, lgtm

#355 fix: make it so fastfetch does not return 1969 as the date on `Forged Date`
  build_scripts/26-packages-post.sh
Labels: bug, size:XS, lgtm

#354 feat: cleanup a few packages that got into EPEL and put requests for ones that arent here yet
  build_scripts/15-packages-image-base.sh
  build_scripts/20-packages.sh
  build_scripts/cleanup.sh
  build_scripts/overrides/dx/00-packages.sh
  build_scripts/overrides/gdx/30-packages.sh
Labels: enhancement, size:M, lgtm

#358 Fix: Slow login times when password is typed wrong
  build_scripts/26-packages-post.sh
  build_scripts/40-services.sh
Labels: bug, size:XS, lgtm

#289 feat: enable SBOM generation
  .github/workflows/reusable-build-image.yml
Labels: enhancement, size:M, lgtm

#360 ci: use wolfi as the base for manifest step
  .github/workflows/reusable-build-image.yml
  build_scripts/cleanup.sh
Labels: enhancement, size:S, lgtm

#362 feat: add buildah to the base image
  build_scripts/20-packages.sh
Labels: enhancement, size:XS, lgtm

#365 chore: disable Renovate for GHA workflow container pinning
  .github/renovate.json5
Labels: dependencies, size:XS, lgtm

#368 feat: Add Ampere logo setter
  system_files/usr/share/ublue-os/user-setup.hooks.d/10-theming.sh
Labels: size:XS

#370 fix: remove rechunk for now and ensure proper kernel is being selected by QUALIFIED_KERNEL
  .github/workflows/reusable-build-image.yml
  build_scripts/26-packages-post.sh
  build_scripts/overrides/gdx/20-nvidia.sh
Labels: size:S

#374 fix: pin C10s to base image built on 4th March 2025
  .github/workflows/reusable-build-image.yml
  Containerfile
Labels: size:S, lgtm

#378 fix: use bind mount for in-repo content
  .github/workflows/reusable-build-image.yml
  Containerfile
  build_scripts/15-packages-image-base.sh
  build_scripts/20-packages.sh
  build_scripts/build.sh
  build_scripts/cleanup.sh
  build_scripts/overrides/x86_64/10-brew.sh
Labels: size:M, lgtm

#380 feat: add nvidia cuda extension for vscode and fix changelog getting wrong package
  .github/changelogs.py
  system_files_overrides/gdx/usr/share/ublue-os/user-setup.hooks.d/30-gdx-vscode.sh
Labels: enhancement, size:S, lgtm

#381 fix: make changelogs have "c10s" instead of "CS10" on their title
  .github/changelogs.py
Labels: size:XS

#366 feat: add k8s tools to dx and some missing flatpaks
  build_scripts/overrides/dx/00-packages.sh
  build_scripts/overrides/dx/05-dconf.sh
  build_scripts/overrides/dx/30-flatpak.sh
Labels: enhancement, size:M, lgtm

#386 fix(just): update build-bib
  Justfile
Labels: size:XS, lgtm

#396 Fix (justfile): make macos compatible
  Justfile
Labels: size:S, lgtm

#389 feat: add demo just for Ampere
  system_files_overrides/aarch64-gdx/usr/share/ublue-os/gdx-demo/bench-container/Dockerfile
  system_files_overrides/aarch64-gdx/usr/share/ublue-os/gdx-demo/ramalama/demo-ai-server.py
  system_files_overrides/aarch64-gdx/usr/share/ublue-os/gdx-demo/ramalama/ramalama-serve-ampere.py
  system_files_overrides/aarch64-gdx/usr/share/ublue-os/just/66-ampere.just
Labels: enhancement, size:L, lgtm, gdx

#393 fix (aarch64): pixi bin to the PATH and add bluefin-cli packages for pixi
  system_files_overrides/aarch64/etc/profile.d/pixi.sh
  system_files_overrides/aarch64/usr/share/ublue-os/homebrew/bluefin-cli_pixi_packages
Labels: size:S, lgtm

#399 feat: try to update to the new centos-bootc bases
  Containerfile
  build_scripts/cleanup.sh
  build_scripts/overrides/aarch64/05-pixi.sh
Labels: enhancement, size:M, lgtm

#404 Fix (ublue-bling): set pixi to default on AARCH64
  system_files_overrides/aarch64/usr/share/ublue-os/homebrew/bling.json
Labels: size:XS, lgtm, arm

#406 fix: put pixi aarch64 configs in the right paths
  system_files_overrides/aarch64/etc/ublue-os/bling.json
  system_files_overrides/aarch64/usr/share/ublue-os/bling/bluefin-cli.pixi.list
Labels: size:XS, lgtm, arm

#413 fix: /usr/local not writeable
  build_scripts/cleanup.sh
Labels: bug, size:XS, lgtm

#418 fix(ublue-bling): remove system override copy for the brewfiles
  system_files_overrides/x86_64/.gitkeep
  system_files_overrides/x86_64/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
  system_files_overrides/x86_64/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: size:S, lgtm
