Repository ublue-os/bluefin-lts, pull requests merged in 2025-07, with the labels that each got.

#567 feat: switch to kmod kernel and add tailscale-exitnode picker
  Justfile
  build_scripts/10-packages-image-base.sh
  build_scripts/26-packages-post.sh
  system_files/usr/libexec/ublue-ts-exit-node
  system_files/usr/share/ublue-os/just/61-lts-custom.just
Labels: enhancement, size:L, lgtm

#569 fix(ujust): add missing colon
  system_files/usr/share/ublue-os/just/61-lts-custom.just
Labels: size:XS, lgtm

#583 fix (build): remove k8s tools installed by curl, to be replaced by brew installed
  build_scripts/overrides/dx/00-packages.sh
Labels: dx, size:M, lgtm

#572 chore: replace Bazaar RPM with Flatpak
  build_scripts/20-packages.sh
Labels: size:S, lgtm

#587 fix: remove use of sudo from kernel pin script
  build_scripts/scripts/pin-kernel.sh
Labels: size:XS, lgtm

#590 fix: kernel pinning - enable allowerasing and remove kernal-module-extras
  build_scripts/scripts/pin-kernel.sh
Labels: size:XS, lgtm

#600 fix: move GNOME 48 backport COPR installation outside of testing block
  build_scripts/10-packages-image-base.sh
Labels: bug, size:XS, lgtm

#603 feat: add hplip
  build_scripts/20-packages.sh
Labels: enhancement, size:XS, lgtm

#613 fix(ci): tag both hwe and testing during push
  .github/workflows/build-regular-hwe.yml
Labels: bug, size:XS, lgtm
