Repository ublue-os/bluefin-lts, pull requests merged in 2025-06, with the labels that each got.

#503 fix: remove ISO workflows
  .github/workflows/build-iso.yml
  iso.toml
  iso_files/configure_iso.sh
Labels: iso, size:L, lgtm

#502 feat: add -testing tag for gnome 48 COPR
  .github/workflows/build-regular.yml
  .github/workflows/reusable-build-image.yml
  Containerfile
  Justfile
  build_scripts/10-packages-image-base.sh
Labels: enhancement, size:M, lgtm

#504 chore(ci): don't push on PRs
  .github/workflows/build-regular.yml
Labels: size:XS, lgtm

#509 fix(testing): add glib2
  build_scripts/10-packages-image-base.sh
Labels: size:XS, lgtm

#513 fix: remove duplicate "-testing" suffix from image tags
  .github/workflows/reusable-build-image.yml
Labels: size:XS, lgtm

#514 feat(bazaar): add to testing builds using f42's builds
  build_scripts/20-packages.sh
Labels: enhancement, size:S, lgtm

#508 fix(testing): pull in fixed xdg-desktop-portal
  build_scripts/10-packages-image-base.sh
Labels: size:XS, lgtm

#522 revert: "fix: working vscode install GPG check"
  build_scripts/overrides/dx/00-packages.sh
Labels: bug, size:XS, lgtm

#535 fix(nvidia): cuda is no longer in negativo
  build_scripts/overrides/gdx/20-nvidia.sh
Labels: size:XS, lgtm, gdx

#540 Update README.md
  README.md
Labels: documentation, size:XS, lgtm

#548 fix(dx-k8s-packages): update checksum file names for kind binary and kubectl
  build_scripts/overrides/dx/00-packages.sh
Labels: dx, size:XS, lgtm

#550 chore(ci): move to container-storage-action
  .github/workflows/reusable-build-image.yml
Labels: size:XS, lgtm

#551 chore(ci): update reusable-build-image.yml
  .github/workflows/reusable-build-image.yml
Labels: dx, size:XS, lgtm

#553 feat(setup): add atd file fix script for job scheduling
  system_files/usr/share/ublue-os/privileged-setup.hooks.d/20-atd-file-fix.sh
Labels: enhancement, size:S, lgtm

#555 feat(bazaar): add bazaar config
  system_files/usr/share/ublue-os/bazaar/01-bluefin.png
  system_files/usr/share/ublue-os/bazaar/02-bluefin.png
  system_files/usr/share/ublue-os/bazaar/03-bluefin.png
  system_files/usr/share/ublue-os/bazaar/04-bluefin.png
  system_files/usr/share/ublue-os/bazaar/05-bluefin.png
  system_files/usr/share/ublue-os/bazaar/06-bluefin.png
  system_files/usr/share/ublue-os/bazaar/08-bluefin.png
  system_files/usr/share/ublue-os/bazaar/10-bluefin.png
  system_files/usr/share/ublue-os/bazaar/11-bluefin.png
  system_files/usr/share/ublue-os/bazaar/12-bluefin.png
  system_files/usr/share/ublue-os/bazaar/blocklist.txt
  system_files/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, size:L, lgtm

#556 feat(build-scripts): add nss-mdns, remove gnome-extensions, remove jreilly COPR
  build_scripts/10-packages-image-base.sh
  build_scripts/20-packages.sh
Labels: enhancement, size:XS, lgtm
