Repository ublue-os/bluefin-lts, pull requests merged in 2025-01, with the labels that each got.

#185 feat: virt-manager, solaar and input-leap as flatpaks
  system_files/etc/ublue-os/system-flatpaks.list
Labels: enhancement, size:XS, lgtm

#186 chore(ci): move to a weekly schedule
  .github/workflows/build-image.yml
Labels: size:XS, lgtm

#191 feat: set lock layering to true
  system_files/etc/rpm-ostreed.conf
Labels: enhancement, size:XS, lgtm

#190 chore(ci): delete .github/workflows/cleanup-old-images.yaml
  .github/workflows/cleanup-old-images.yaml
Labels: size:S, lgtm

#189 chore(ci): enable pushing to bluefin:lts
  .github/changelogs.py
  .github/workflows/build-image.yml
  .github/workflows/build-iso.yml
  Justfile
  README.md
  image-builder-iso.config.toml
Labels: size:S, lgtm

#193 docs: update README.md
  README.md
Labels: size:XS, lgtm

#197 feat: merge everything from main to this + remove tons of workarounds and clean up stuff
  Containerfile
  build_scripts/00-workarounds.sh
  build_scripts/10-image-info.sh
  build_scripts/15-packages-image-base.sh
  build_scripts/20-packages.sh
  build_scripts/26-packages-post.sh
  build_scripts/40-services.sh
  build_scripts/build.sh
Labels: enhancement, size:L, lgtm

#199 feat: enable hibernation on initramfs
  build_scripts/26-packages-post.sh
Labels: enhancement, size:XS, lgtm

#198 feat: add extensions that are missing from bluefin
  build_scripts/20-packages.sh
Labels: enhancement, size:XS, lgtm

#200 feat: enable sleep-then-hiberate by default
  build_scripts/40-services.sh
  system_files/usr/lib/systemd/sleep.conf.d/hibernation.conf
Labels: enhancement, size:XS, lgtm

#201 fix: set hibernation timer to 60m
  system_files/usr/lib/systemd/sleep.conf.d/hibernation.conf
Labels: size:XS, lgtm

#204 feat: add dx, hwe and arm support to the Containerfile inwards
  Containerfile
  Justfile
  build_scripts/build.sh
  build_scripts/cleanup.sh
  build_scripts/overrides/aarch64/.gitkeep
  build_scripts/overrides/dx/00-packages.sh
  build_scripts/overrides/hwe/.gitkeep
  build_scripts/overrides/x86_64/10-brew.sh
  system_files_overrides/aarch64/.gitkeep
  system_files_overrides/dx/.gitkeep
  system_files_overrides/hwe/.gitkeep
  system_files_overrides/x86_64/.gitkeep
Labels: enhancement, size:M, lgtm

#203 feat: enable arm builds
  .github/workflows/build-image.yml
  Justfile
Labels: enhancement, size:L, lgtm

#210 fix: append -lts to ISO name
  .github/workflows/build-iso.yml
Labels: size:XS, lgtm
