Repository ublue-os/bluefin-lts, pull requests merged in 2025-02, with the labels that each got.

#216 feat: enable workflows for dx and hwe
  .github/workflows/build-image.yml
  .github/workflows/build-iso.yml
Labels: enhancement, size:M, lgtm

#218 fix: delete systemd/sleep.conf.d/hibernation.conf
  system_files/usr/lib/systemd/sleep.conf.d/hibernation.conf
Labels: size:XS, lgtm

#219 fix: refactor workflow to support multiple images
  .github/workflows/build-dx-hwe.yml
  .github/workflows/build-dx.yml
  .github/workflows/build-hwe.yml
  .github/workflows/build-regular.yml
  .github/workflows/reusable-build-image.yml
Labels: size:L, lgtm

#215 chore: replace x86_64-only Flatpaks with amd64 alternatives
  .github/workflows/build-iso.yml
  build_scripts/build.sh
  build_scripts/overrides/aarch64/00-flatpaks.sh
Labels: enhancement, size:M, lgtm

#220 fix: use ublue-os signing key
  cosign.pub
Labels: size:XS, lgtm

#221 fix: inherit secrets in reusable workflow
  .github/workflows/build-dx-hwe.yml
  .github/workflows/build-dx.yml
  .github/workflows/build-hwe.yml
  .github/workflows/build-regular.yml
  .github/workflows/reusable-build-image.yml
Labels: size:XS, lgtm

#227 fix(ci): ensure we always run the manifest step
  .github/workflows/reusable-build-image.yml
Labels: size:S, lgtm

#222 feat: add ublue-os-signing for container signing :)
  build_scripts/20-packages.sh
  image-builder-iso.config.toml
Labels: enhancement, size:XS, lgtm

#224 feat: add support for -dx and -hwe specific for arches
  build_scripts/build.sh
  build_scripts/overrides/aarch64/dx/.gitkeep
  build_scripts/overrides/aarch64/hwe/.gitkeep
  build_scripts/overrides/x86_64/10-brew.sh
  build_scripts/overrides/x86_64/dx/.gitkeep
  build_scripts/overrides/x86_64/hwe/.gitkeep
  system_files_overrides/aarch64-dx/.gitkeep
  system_files_overrides/aarch64-hwe/.gitkeep
  system_files_overrides/x86_64-dx/.gitkeep
  system_files_overrides/x86_64-hwe/.gitkeep
Labels: enhancement, size:XS, lgtm

#228 chore: move from Achillobator to Bluefin LTS on the os-release string
  build_scripts/10-image-info.sh
Labels: size:XS, lgtm

#229 feat: add caffeine extension from staging
  build_scripts/20-packages.sh
Labels: enhancement, size:XS, lgtm

#225 fix: set UBLUE_CONFIG_DIR in theming script
  system_files/etc/ublue-os/setup.json
  system_files/usr/share/ublue-os/user-setup.hooks.d/10-theming.sh
Labels: size:XS, lgtm

#230 feat: use ublue-changelogs for changelog viewing
  system_files/etc/ublue-os/changelog.json
  system_files/usr/share/ublue-os/just/10-update.just
Labels: enhancement, size:XS, lgtm

#233 chore: remove boxbuddy from non-dx images
  build_scripts/26-packages-post.sh
  build_scripts/overrides/dx/05-dconf.sh
Labels: size:S, lgtm

#226 feat: add pixi for aarch64 builds
  build_scripts/overrides/aarch64/05-pixi.sh
Labels: enhancement, size:XS, lgtm

#234 chore(ci): remove unnecessary build on push
  .github/workflows/build-dx-hwe.yml
  .github/workflows/build-dx.yml
  .github/workflows/build-hwe.yml
  .github/workflows/build-regular.yml
  .github/workflows/reusable-build-image.yml
Labels: size:M, lgtm

#235 fix: ensure suspend-then-hibernate is the default sleep option
  build_scripts/40-services.sh
Labels: size:XS, lgtm

#237 fix: make build.sh less verbose so we can click on the arrows
  build_scripts/build.sh
Labels: size:XS, lgtm

#239 fix: make signing come as late as possible on the build
  build_scripts/20-packages.sh
  build_scripts/cleanup.sh
Labels: size:S, lgtm

#236 feat: add hyperscale kernel from Koji builds
  build_scripts/overrides/hwe/.gitkeep
  build_scripts/overrides/hwe/10-hyperscale-kernel.sh
Labels: enhancement, size:S, lgtm

#244 fix: make signing actually work!
  build_scripts/build.sh
  build_scripts/cleanup.sh
Labels: size:XS, lgtm

#243 feat: add nvidia-open and hyperscale kernel from their repos
  build_scripts/build.sh
  build_scripts/overrides/hwe/10-hyperscale-kernel.sh
  build_scripts/overrides/x86_64/hwe/20-nvidia.sh
Labels: enhancement, size:M, lgtm

#245 fix: sign manifest with cosign
  .github/workflows/reusable-build-image.yml
Labels: size:M, lgtm

#247 feat: add bluefin GDX edition for nvidia graphics card development
  .github/workflows/build-gdx.yml
  .github/workflows/reusable-build-image.yml
  Containerfile
  Justfile
  build_scripts/build.sh
  build_scripts/overrides/x86_64/gdx/20-nvidia.sh
  system_files_overrides/x86_64-gdx/.gitkeep
Labels: enhancement, size:M, lgtm

#249 ci: add ISO building for hwe and gdx
  .github/workflows/build-iso.yml
Labels: enhancement, size:S, lgtm

#250 fix: use inputs for single-arch images
  .github/workflows/build-gdx.yml
  .github/workflows/reusable-build-image.yml
Labels: size:S, lgtm

#253 fix: make sure nouveau kargs are getting applied on nvidia builds
  build_scripts/15-packages-image-base.sh
  build_scripts/overrides/hwe/10-hyperscale-kernel.sh
  build_scripts/overrides/x86_64/gdx/20-nvidia.sh
Labels: size:S, lgtm

#255 fix: make nvidia-open kernel modules build on container build
  build_scripts/00-workarounds.sh
  build_scripts/overrides/x86_64/gdx/20-nvidia.sh
Labels: bug, size:M, lgtm

#261 fix: build ARM64 ISOs except for gdx
  .github/workflows/build-iso.yml
Labels: size:XS

#266 fix: ensure we have complete systemd on the images
  build_scripts/15-packages-image-base.sh
  build_scripts/20-packages.sh
Labels: size:XS, lgtm

#263 feat(dx): add uv, pixi and ramalama
  Containerfile
  build_scripts/overrides/dx/00-packages.sh
  build_scripts/overrides/dx/10-pixi.sh
  system_files_overrides/dx/usr/bin/.gitkeep
Labels: enhancement, size:S, lgtm

#268 feat: add flathub by default on-image
  build_scripts/26-packages-post.sh
Labels: enhancement, size:XS, lgtm

#273 fix: disable vscode update dialog
  system_files_overrides/dx/etc/skel/.config/Code/User/settings.json
Labels: dx, parity, size:XS, lgtm

#272 docs: Add documentation for Justfile recipes
  Justfile
Labels: documentation, size:L, lgtm

#284 feat: add CentOS version number tags
  .github/workflows/reusable-build-image.yml
Labels: enhancement, size:XS, lgtm

#290 feat: add libcamera for webcams
  build_scripts/15-packages-image-base.sh
Labels: enhancement, size:XS

#291 chore: remove brew tarball as ublue-brew already provides it as of 0.1.2
  build_scripts/overrides/x86_64/10-brew.sh
Labels: size:S, lgtm

#288 feat: add Nerd Fonts to VSCode (#287)
  system_files/etc/skel/.config/Code/User/system_files/etc/skel/.config/Code/User/settings.json
Labels: enhancement, size:XS, lgtm

#292 fix: kernel package skews because of compose repos getting disabled too early in build
  build_scripts/26-packages-post.sh
  build_scripts/cleanup.sh
  build_scripts/overrides/x86_64/gdx/20-nvidia.sh
Labels: size:S, lgtm

#293 fix: enable fingerprint sensors polkit rule by default via authselect
  build_scripts/26-packages-post.sh
Labels: size:XS, lgtm

#304 fix: use epel-release from centos repos
  build_scripts/15-packages-image-base.sh
Labels: size:XS, lgtm

#303 fix: make sure image-info has proper names + apply os-release last
  build_scripts/90-image-info.sh
  build_scripts/build.sh
  build_scripts/overrides/dx/90-image-info.sh
  build_scripts/overrides/hwe/.gitkeep
  build_scripts/overrides/hwe/90-image-info.sh
  build_scripts/overrides/x86_64/gdx/90-image-info.sh
  build_scripts/scripts/image-info-set
Labels: size:M, lgtm

#297 feat: add ublue-rebase-helper and dx-helper for devmode
  build_scripts/20-packages.sh
  system_files/etc/ublue-os/rebase_helper.json
  system_files/usr/share/ublue-os/just/60-custom.just
Labels: enhancement, size:S, lgtm

#309 chore: install uv from EPEL instead of copr/container image
  Containerfile
  build_scripts/20-packages.sh
  build_scripts/40-services.sh
  build_scripts/overrides/x86_64/gdx/30-packages.sh
Labels: dependencies, size:M, lgtm

#315 chore: pass the entire repo through shfmt and shellcheck
  Justfile
  build_scripts/00-workarounds.sh
  build_scripts/build.sh
  build_scripts/overrides/aarch64/00-flatpaks.sh
  build_scripts/overrides/dx/05-dconf.sh
  build_scripts/overrides/x86_64/gdx/20-nvidia.sh
  image.toml
  iso.toml
  system_files/etc/skel/.config/Code/User/system_files/etc/skel/.config/Code/User/settings.json
  system_files/usr/share/containers/storage.conf
  system_files/usr/share/fish/vendor_functions.d/fish_prompt.fish
  system_files/usr/share/ublue-os/user-setup.hooks.d/10-theming.sh
  system_files_overrides/hwe/usr/share/ublue-os/system-setup.hooks.d/10-framework-and-nvidia.sh
Labels: size:L, lgtm

#317 chore: remove unnecessary workaround on global environment and add note about other workarounds
  system_files/etc/environment
Labels: size:XS, lgtm

#319 feat: add nvtop and use epel version of staging copr for packages
  build_scripts/20-packages.sh
  build_scripts/overrides/x86_64/gdx/30-packages.sh
Labels: enhancement, size:XS

#321 chore: move COPR packages to new `ublue-os` coprs
  Containerfile
  build_scripts/20-packages.sh
  build_scripts/40-services.sh
  build_scripts/cleanup.sh
  build_scripts/overrides/x86_64/10-brew.sh
Labels: size:M, lgtm

#324 fix(changelogs): Don't look for Fedora Version
  .github/changelogs.py
Labels: size:XS, lgtm

#327 fix: update brew copr
  build_scripts/overrides/x86_64/10-brew.sh
Labels: size:XS, lgtm

#328 fix: move from staging to packages COPR
  build_scripts/20-packages.sh
Labels: size:XS

#325 fix(just): add if-not-exists switch to install-system-flatpaks
  system_files/usr/share/ublue-os/just/60-custom.just
Labels: size:XS, lgtm

#331 feat: add polkit/sudo rules for bootc and passkeys
  build_scripts/20-packages.sh
Labels: enhancement, size:XS, lgtm

#332 feat: add system-reinstall-bootc for powerwash feature
  build_scripts/20-packages.sh
Labels: enhancement, size:XS, lgtm

#338 fix: drop gsconnect as EPEL has broken dependencies for ffmpeg right now
  build_scripts/15-packages-image-base.sh
  build_scripts/20-packages.sh
Labels: dependencies, size:XS, lgtm

#336 fix: fix custom just
  build_scripts/15-packages-image-base.sh
  build_scripts/26-packages-post.sh
  system_files/usr/share/ublue-os/just/61-lts-custom.just
Labels: size:XS, lgtm

#342 fix: keep the kernel versionlock on GDX
  build_scripts/overrides/gdx/20-nvidia.sh
Labels: size:S, lgtm

#343 chore: update the kernel on build + add gsconnect just for aarch64 for now + attempt to fix systemd-resolved
  build_scripts/00-workarounds.sh
  build_scripts/15-packages-image-base.sh
  build_scripts/20-packages.sh
  build_scripts/overrides/gdx/20-nvidia.sh
Labels: size:S, lgtm

#335 fix: Permission denied with image-info.json
  build_scripts/cleanup.sh
  build_scripts/scripts/image-info-set
Labels: bug, size:XS, lgtm

#346 feat: make ublue user services work with helper script
  system_files/usr/share/ublue-os/privileged-setup.hooks.d/10-tailscale.sh
  system_files/usr/share/ublue-os/privileged-setup.hooks.d/99-flatpaks.sh
  system_files/usr/share/ublue-os/user-setup.hooks.d/10-theming.sh
  system_files/usr/share/ublue-os/user-setup.hooks.d/99-flatpaks.sh
  system_files/usr/share/ublue-os/user-setup.hooks.d/99-privileged.sh
  system_files_overrides/dx/usr/share/ublue-os/privileged-setup.hooks.d/20-dx.sh
  system_files_overrides/dx/usr/share/ublue-os/user-setup.hooks.d/11-vscode.sh
Labels: enhancement, size:L, lgtm
