Repository ublue-os/bluefin-lts, pull requests merged in 2025-04, with the labels that each got.

#422 chore: reenable SBOMs
  .github/workflows/reusable-build-image.yml
Labels: size:XS, lgtm

#428 Fix(cleanup): there's no fish desktop file
  build_scripts/cleanup.sh
Labels: size:XS, lgtm

#429 fix: match ID in os-release correctly
  build_scripts/90-image-info.sh
Labels: bug, size:XS, lgtm

#432 fix: use official EPEL rpm provided by fedora
  build_scripts/15-packages-image-base.sh
Labels: size:XS, lgtm

#430 fix: improve parsing of MAJOR_VERSION_NUMBER
  build_scripts/build.sh
Labels: size:XS, lgtm

#425 Fix(dirs): add symlink for /opt
  Containerfile
Labels: size:XS, lgtm

#437 feat: use hyperscale kernel and go all in on HWE by default
  .github/changelogs.py
  .github/workflows/build-dx-hwe.yml
  .github/workflows/build-hwe.yml
  .github/workflows/build-iso.yml
  .github/workflows/reusable-build-image.yml
  Containerfile
  Justfile
  build_scripts/10-packages-image-base.sh
  build_scripts/build.sh
  build_scripts/overrides/gdx/20-nvidia.sh
  build_scripts/overrides/hwe/90-image-info.sh
  build_scripts/overrides/x86_64/hwe/10-hyperscale-kernel.sh
  system_files/usr/share/ublue-os/system-setup.hooks.d/10-framework-and-nvidia.sh
  system_files_overrides/aarch64-hwe/.gitkeep
  system_files_overrides/x86_64-hwe/.gitkeep
Labels: enhancement, size:L, lgtm

#435 chore: rename ID to bluefin_lts instead of `bluefin LTS`
  build_scripts/90-image-info.sh
Labels: size:XS, lgtm

#436 feat: add k0s and kubectl + cleanup a few things on build
  Containerfile
  build_scripts/20-packages.sh
  build_scripts/cleanup.sh
  build_scripts/overrides/dx/00-packages.sh
  build_scripts/overrides/gdx/30-packages.sh
Labels: enhancement, size:M, lgtm

#439 fix: enable hyperscale repos during anaconda install
  .github/workflows/build-iso.yml
  iso_files/configure_iso.sh
Labels: iso, size:XS, lgtm

#440 feat: add xhost
  build_scripts/20-packages.sh
Labels: enhancement, parity, size:XS, lgtm

#441 fix: permissions for image-info json file
  build_scripts/cleanup.sh
Labels: bug, size:XS

#443 feat(ci): add image-versions.yaml
  image-versions.yaml
Labels: enhancement, size:XS, lgtm

#444 fix: update image-versions.yaml digest syntax
  image-versions.yaml
Labels: size:XS

#446 feat(ci): automerge when upstream image updates
  .github/renovate.json5
Labels: size:XS, lgtm

#451 fix: use dnf swap centos-logos earlier because of a conflict w/ bluefin-plymouth
  build_scripts/20-packages.sh
Labels: size:XS, lgtm

#452 chore: CODEOWNERS is invalid
  .github/CODEOWNERS
Labels: size:XS, lgtm

#464 fix(arm): switch browser back to firefox
  build_scripts/overrides/aarch64/00-flatpaks.sh
Labels: size:S, lgtm, arm

#465 fix: make it so gdx builds
  build_scripts/10-packages-image-base.sh
  build_scripts/overrides/gdx/20-nvidia.sh
Labels: dependencies, size:XS, lgtm, gdx

#462 chore: remove image-versions.yml from codeowners
  .github/CODEOWNERS
Labels: size:XS, lgtm

#468 feat: add offline bluefin documentation to `/usr/share/doc`
  build_scripts/26-packages-post.sh
Labels: documentation, enhancement, size:XS, lgtm

#469 fix: disable distrobox module on uupd
  build_scripts/40-services.sh
Labels: size:XS, lgtm

#470 Revert "fix: disable distrobox module on uupd"
  build_scripts/40-services.sh
Labels: size:XS

#471 feat: attempt to use negativo's epel-multimedia repo for ffmpeg
  build_scripts/10-packages-image-base.sh
Labels: enhancement, size:XS, lgtm
