Repository ublue-os/bluefin-lts, pull requests merged in 2025-09, with the labels that each got.

#702 README: Stream10 -> Stream 10
  README.md
Labels: size:XS, lgtm

#718 fix(base): extensions-app begone
  build_scripts/20-packages.sh
Labels: bug, size:XS, lgtm

#730 feat: add wireguard-tools and openconnect
  build_scripts/20-packages.sh
Labels: enhancement, size:XS, lgtm

#689 feat: ZFS and Nvidia AKMODS for LTS, DX, GDX, and HWE variants.
  .github/workflows/reusable-build-image.yml
  .gitignore
  Containerfile
  Justfile
  build_scripts/10-packages-image-base.sh
  build_scripts/overrides/gdx/20-nvidia.sh
  build_scripts/overrides/x86_64/20-zfs.sh
  build_scripts/scripts/kernel-swap.sh
  build_scripts/scripts/pin-kernel.sh
Labels: enhancement, size:L, lgtm

#744 fix(glib2): pin after installation
  build_scripts/10-packages-image-base.sh
Labels: size:XS
